### ISSUE TITLE
Grubbed slide disordered

### ISSUE THREAD

**Issue by ghost** [cballenar/slideshare-to-pdf#1]
the tool grabbed all the slides 48/48, but they are disordered comparing to the original ones.
https://www.slideshare.net/echi99/genotype-imputation-via-matrix-completion-15496007
thanks

**Comment by ombir** [comment]
Same here. Tried to download a private presentation with Authentication Code(hmac) in url. Grabbed all by disordered in pdf. Please check.

**Comment by cballenar** [comment]
Thanks for the feedback. The latest commit should take care of the issue.

This tool is on its way out, I've moved most of the development to [SlideGrubber](https://github.com/cballenar/slidegrubber) which can be installed as a python package. Unfortunately I think it currently has the same issue, I'll work on that next.
